spring:
  datasource:
    #url: jdbc:mysql://localhost:3307/cafe?serverTimezone=Asia/Seoul
    #username: root          # 본인의 로컬 DB 사용자명
    #password: 1234          # 본인의 로컬 DB 비밀번호
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cafe-db.co1m44gsm48y.us-east-1.rds.amazonaws.com:3306/cafe
    username: admin          # 본인의 로컬 DB 사용자명
    password: cafe1234          # 본인의 로컬 DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      # 파일당 최대 크기 (50MB)
      max-file-size: 50MB
      # 요청당 최대 크기 (55MB)
      max-request-size: 55MB
app:
  file:
    # 1. 파일을 실제로 저장할 서버의 물리적 경로 (upload-dir)
    # 반드시 애플리케이션이 실행되는 계정(여기서는 admin)의 쓰기 권한이 있는 곳이어야 합니다.
    upload-dir: C:/Users/admin/upload-data/cafe_images

    # 2. 웹 브라우저가 이미지에 접근할 때 사용할 URL 경로의 접두사 (base-url)
    # 이 경로는 WebMvcConfig에서 물리적 경로로 매핑됩니다.
    base-url: /images/