# src/main/resources/application-local.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 7241
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

file:
  path: /Users/jeon/supernova-upload/img/