spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cafe?serverTimezone=Asia/Seoul
    username: root          # 본인의 로컬 DB 사용자명
    password: 1234          # 본인의 로컬 DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver