# ----------------------------------------
# 공통 설정 (팀원 공유)
# ----------------------------------------
spring:
  # 기본으로 활성화할 프로파일을 정하고, 개인 설정으로 덮어씁니다.
  # 개인 PC에서 실행할 때는 -Dspring.profiles.active=local 등으로 덮어쓰도록 유도
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      # 파일당 최대 크기 (50MB)
      max-file-size: 50MB
      # 요청당 최대 크기 (55MB)
      max-request-size: 55MB

app:
  file:
    # 1. 파일을 실제로 저장할 서버의 물리적 경로 (upload-dir)
    # 반드시 애플리케이션이 실행되는 계정(여기서는 admin)의 쓰기 권한이 있는 곳이어야 합니다.
    upload-dir: C:/Users/admin/upload-data/cafe_images

    # 2. 웹 브라우저가 이미지에 접근할 때 사용할 URL 경로의 접두사 (base-url)
    # 이 경로는 WebMvcConfig에서 물리적 경로로 매핑됩니다.
    base-url: /images/

  jpa:
    hibernate:
      ddl-auto: update                          # DDL 전략 통일 (개발 환경 기준)
    properties:
      hibernate:
        format_sql: true                        # SQL 포맷팅
        show_sql: true                          # SQL 출력
    database-platform: org.hibernate.dialect.MySQL8Dialect # DB 방언 통일
    show-sql: true                              # (팀원 2의 방식) SQL 출력

  output:
    ansi:
      enabled: always                           # 컬러 로그 (선택사항이나, 보기 좋음)

# 이미지 저장 경로 설정
file:
  path: /Users/jeon/supernova-upload/img/

# 공통 로깅 설정 (팀원 2의 상세 로깅 방식을 채택)
logging:
  level:
    # SQL 파라미터, 결과, 트랜잭션 등 공통 디버깅에 필요한 로그 레벨 통일
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE