spring:
  datasource:
    #url: jdbc:mysql://localhost:3307/cafe?serverTimezone=Asia/Seoul
    #username: root          # 본인의 로컬 DB 사용자명
    #password: 1234          # 본인의 로컬 DB 비밀번호
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cafe-db.co1m44gsm48y.us-east-1.rds.amazonaws.com:3306/cafe
    username: admin          # 본인의 로컬 DB 사용자명
    password: cafe1234          # 본인의 로컬 DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver